services:

  frontend:
    build: 
      context: ./frontend
      args:
        VITE_API_URL: "/api"
    depends_on:
      - backend
    command: >
      sh -c "
      npm install &&
      npm run dev -- --host"

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/mydb?schema=public"
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: "http://localhost:5173"

    command: >
      sh -c "
      npx wait-on tcp:db:5432 &&
      npx prisma migrate deploy &&
      npm start"
    
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend