services:

  frontend:
    build: 
      context: ./frontend
      args:
        VITE_API_URL: "http://localhost:3000"

    ports:
      - "5173:5173"
    depends_on:
      - backend
    command: >
      sh -c "
      npm install &&
      npm run dev -- --host"

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/mydb?schema=public"
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      JWT_SECRET: ${JWT_SECRET}

    command: >
      sh -c "
      npx wait-on tcp:db:5432 &&
      npx prisma migrate deploy &&
      npm start"
    
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"