services:

  frontend:
    build: 
      context: ./frontend
      args:
        VITE_API_URL: "/api"
    depends_on:
      - backend
    ports:
      - "5173:5173"  # Host port 5173 → Container port 5173
    command: >
      sh -c "
      npm install &&
      npm run dev -- --host"

  backend:
    build: ./backend
    depends_on:
      - db
    env_file: .env
    ports:
      - "3000:3000"  # Host port 3000 → Container port 3000
    command: >
      sh -c "
      npx wait-on tcp:db:5432 &&
      npx prisma migrate deploy &&
      npm start"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
